### ISSUE TITLE
手機版右下角密碼顯示會歪掉並且超出介面小螢幕範圍唷

### ISSUE THREAD

**Issue by jaliao** [adon988/cooc.azurewebsites.test#21]
手機版右下角密碼顯示會歪掉並且超出介面小螢幕範圍唷
![545575](https://user-images.githubusercontent.com/12048035/99413588-e7db2580-2930-11eb-9516-f4f30471c683.jpg)

**Comment by adon988** [comment]
數字是原始圖片，原始設計就有斜度

**Comment by jaliao** [comment]
目前部分手機仍有壓到線的問題 ( EX iPhone 10 )

**Comment by jaliao** [comment]
第二個密碼 和 第三個密碼 數字要再置中一點

**Comment by jaliao** [comment]
已完成
