### ISSUE TITLE
麻煩幫我先設定理化部分只能顯示萬有引力的影片選項喔！

### ISSUE THREAD

**Issue by jaliao** [adon988/cooc.azurewebsites.test#24]
因為記者會當天的特殊需求
先設定理化部分只能顯示萬有引力的影片選項喔！
到隔天之後才打開

**Comment by adon988** [comment]
/app/Http/Controllers/GameController.php
新增設定：
`$this->customVideo = true;`

**Comment by jaliao** [comment]
確認
